/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FormulaStep = IDL.Record({
  'result' : IDL.Float64,
  'expression' : IDL.Text,
  'name' : IDL.Text,
  'nb777Ref' : IDL.Text,
  'unit' : IDL.Text,
  'substitution' : IDL.Text,
});
export const CircuitType = IDL.Variant({
  'lighting' : IDL.Null,
  'power' : IDL.Null,
  'common' : IDL.Null,
});
export const CircuitDesign = IDL.Record({
  'id' : IDL.Text,
  'totalPowerVA' : IDL.Float64,
  'formulaSteps' : IDL.Vec(FormulaStep),
  'correctedCurrentA' : IDL.Float64,
  'voltageDropPct' : IDL.Float64,
  'cableSectionMm2' : IDL.Float64,
  'description' : IDL.Text,
  'compliesNB777' : IDL.Bool,
  'warnings' : IDL.Vec(IDL.Text),
  'itmAmperes' : IDL.Nat,
  'circuitType' : CircuitType,
  'nominalCurrentA' : IDL.Float64,
  'points' : IDL.Nat,
});
export const TransformerResult = IDL.Record({
  'formulaSteps' : IDL.Vec(FormulaStep),
  'primaryCurrentA' : IDL.Float64,
  'selectedKVA' : IDL.Float64,
  'requiredKVA' : IDL.Float64,
  'secondaryCurrentA' : IDL.Float64,
  'isExistingAdequate' : IDL.Opt(IDL.Bool),
});
export const EnergyEstimate = IDL.Record({
  'dailyUsageHours' : IDL.Float64,
  'dailyKWh' : IDL.Float64,
  'estimatedMonthlyCostBs' : IDL.Float64,
  'monthlyKWh' : IDL.Float64,
});
export const ProjectId = IDL.Text;
export const InstallationType = IDL.Variant({
  'residential' : IDL.Null,
  'industrial' : IDL.Null,
});
export const LuminaireLoad = IDL.Record({
  'typ' : IDL.Text,
  'unitPowerW' : IDL.Float64,
  'quantity' : IDL.Nat,
});
export const TransformerMode = IDL.Variant({
  'own' : IDL.Null,
  'existing' : IDL.Null,
});
export const PowerOutletLoad = IDL.Record({
  'voltage' : IDL.Float64,
  'efficiency' : IDL.Float64,
  'name' : IDL.Text,
  'powerKW' : IDL.Float64,
  'isWetArea' : IDL.Bool,
  'cosPhi' : IDL.Float64,
});
export const ConductorInsulation = IDL.Variant({
  'pvc' : IDL.Null,
  'xlpe' : IDL.Null,
});
export const ConductorMaterial = IDL.Variant({
  'aluminum' : IDL.Null,
  'copper' : IDL.Null,
});
export const ConductorType = IDL.Record({
  'insulation' : ConductorInsulation,
  'material' : ConductorMaterial,
});
export const VoltageSystem = IDL.Variant({
  'tri220' : IDL.Null,
  'tri380' : IDL.Null,
  'mono220' : IDL.Null,
});
export const CommonOutletLoad = IDL.Record({ 'quantity' : IDL.Nat });
export const ProjectInput = IDL.Record({
  'installationType' : InstallationType,
  'luminaires' : IDL.Vec(LuminaireLoad),
  'existingTransformerKVA' : IDL.Opt(IDL.Float64),
  'transformerMode' : TransformerMode,
  'floors' : IDL.Nat,
  'name' : IDL.Text,
  'ambientTempC' : IDL.Float64,
  'powerOutlets' : IDL.Vec(PowerOutletLoad),
  'totalAreaM2' : IDL.Float64,
  'distanceToTransformerM' : IDL.Float64,
  'conductorType' : ConductorType,
  'voltageSystem' : VoltageSystem,
  'initialPowerFactor' : IDL.Float64,
  'commonOutlets' : IDL.Vec(CommonOutletLoad),
});
export const PowerFactorCompensation = IDL.Record({
  'reactiveKVAR' : IDL.Float64,
  'formulaSteps' : IDL.Vec(FormulaStep),
  'suggestedBankKVAR' : IDL.Float64,
  'needed' : IDL.Bool,
  'capacitorMicroFarads' : IDL.Float64,
});
export const CalculationResult = IDL.Record({
  'circuits' : IDL.Vec(CircuitDesign),
  'shortCircuitFormulaSteps' : IDL.Vec(FormulaStep),
  'transformer' : IDL.Opt(TransformerResult),
  'asciiFloorPlan' : IDL.Text,
  'energyEstimate' : EnergyEstimate,
  'totalInstalledPowerVA' : IDL.Float64,
  'projectId' : ProjectId,
  'materialsList' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Text)),
  'temperatureFactor' : IDL.Float64,
  'shortCircuitCurrentA' : IDL.Float64,
  'input' : ProjectInput,
  'asciiSingleLineDiagram' : IDL.Text,
  'globalWarnings' : IDL.Vec(IDL.Text),
  'groupingFactor' : IDL.Float64,
  'demandFormulaSteps' : IDL.Vec(FormulaStep),
  'lineCurrentA' : IDL.Float64,
  'powerFactorCompensation' : PowerFactorCompensation,
  'maxDemandVA' : IDL.Float64,
});
export const Timestamp = IDL.Int;
export const Project = IDL.Record({
  'id' : ProjectId,
  'result' : IDL.Opt(CalculationResult),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'input' : ProjectInput,
});

export const idlService = IDL.Service({
  'calculateProject' : IDL.Func([IDL.Text], [IDL.Opt(CalculationResult)], []),
  'createProject' : IDL.Func([ProjectInput], [IDL.Text], []),
  'deleteProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'updateProjectInput' : IDL.Func([IDL.Text, ProjectInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FormulaStep = IDL.Record({
    'result' : IDL.Float64,
    'expression' : IDL.Text,
    'name' : IDL.Text,
    'nb777Ref' : IDL.Text,
    'unit' : IDL.Text,
    'substitution' : IDL.Text,
  });
  const CircuitType = IDL.Variant({
    'lighting' : IDL.Null,
    'power' : IDL.Null,
    'common' : IDL.Null,
  });
  const CircuitDesign = IDL.Record({
    'id' : IDL.Text,
    'totalPowerVA' : IDL.Float64,
    'formulaSteps' : IDL.Vec(FormulaStep),
    'correctedCurrentA' : IDL.Float64,
    'voltageDropPct' : IDL.Float64,
    'cableSectionMm2' : IDL.Float64,
    'description' : IDL.Text,
    'compliesNB777' : IDL.Bool,
    'warnings' : IDL.Vec(IDL.Text),
    'itmAmperes' : IDL.Nat,
    'circuitType' : CircuitType,
    'nominalCurrentA' : IDL.Float64,
    'points' : IDL.Nat,
  });
  const TransformerResult = IDL.Record({
    'formulaSteps' : IDL.Vec(FormulaStep),
    'primaryCurrentA' : IDL.Float64,
    'selectedKVA' : IDL.Float64,
    'requiredKVA' : IDL.Float64,
    'secondaryCurrentA' : IDL.Float64,
    'isExistingAdequate' : IDL.Opt(IDL.Bool),
  });
  const EnergyEstimate = IDL.Record({
    'dailyUsageHours' : IDL.Float64,
    'dailyKWh' : IDL.Float64,
    'estimatedMonthlyCostBs' : IDL.Float64,
    'monthlyKWh' : IDL.Float64,
  });
  const ProjectId = IDL.Text;
  const InstallationType = IDL.Variant({
    'residential' : IDL.Null,
    'industrial' : IDL.Null,
  });
  const LuminaireLoad = IDL.Record({
    'typ' : IDL.Text,
    'unitPowerW' : IDL.Float64,
    'quantity' : IDL.Nat,
  });
  const TransformerMode = IDL.Variant({
    'own' : IDL.Null,
    'existing' : IDL.Null,
  });
  const PowerOutletLoad = IDL.Record({
    'voltage' : IDL.Float64,
    'efficiency' : IDL.Float64,
    'name' : IDL.Text,
    'powerKW' : IDL.Float64,
    'isWetArea' : IDL.Bool,
    'cosPhi' : IDL.Float64,
  });
  const ConductorInsulation = IDL.Variant({
    'pvc' : IDL.Null,
    'xlpe' : IDL.Null,
  });
  const ConductorMaterial = IDL.Variant({
    'aluminum' : IDL.Null,
    'copper' : IDL.Null,
  });
  const ConductorType = IDL.Record({
    'insulation' : ConductorInsulation,
    'material' : ConductorMaterial,
  });
  const VoltageSystem = IDL.Variant({
    'tri220' : IDL.Null,
    'tri380' : IDL.Null,
    'mono220' : IDL.Null,
  });
  const CommonOutletLoad = IDL.Record({ 'quantity' : IDL.Nat });
  const ProjectInput = IDL.Record({
    'installationType' : InstallationType,
    'luminaires' : IDL.Vec(LuminaireLoad),
    'existingTransformerKVA' : IDL.Opt(IDL.Float64),
    'transformerMode' : TransformerMode,
    'floors' : IDL.Nat,
    'name' : IDL.Text,
    'ambientTempC' : IDL.Float64,
    'powerOutlets' : IDL.Vec(PowerOutletLoad),
    'totalAreaM2' : IDL.Float64,
    'distanceToTransformerM' : IDL.Float64,
    'conductorType' : ConductorType,
    'voltageSystem' : VoltageSystem,
    'initialPowerFactor' : IDL.Float64,
    'commonOutlets' : IDL.Vec(CommonOutletLoad),
  });
  const PowerFactorCompensation = IDL.Record({
    'reactiveKVAR' : IDL.Float64,
    'formulaSteps' : IDL.Vec(FormulaStep),
    'suggestedBankKVAR' : IDL.Float64,
    'needed' : IDL.Bool,
    'capacitorMicroFarads' : IDL.Float64,
  });
  const CalculationResult = IDL.Record({
    'circuits' : IDL.Vec(CircuitDesign),
    'shortCircuitFormulaSteps' : IDL.Vec(FormulaStep),
    'transformer' : IDL.Opt(TransformerResult),
    'asciiFloorPlan' : IDL.Text,
    'energyEstimate' : EnergyEstimate,
    'totalInstalledPowerVA' : IDL.Float64,
    'projectId' : ProjectId,
    'materialsList' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Text)),
    'temperatureFactor' : IDL.Float64,
    'shortCircuitCurrentA' : IDL.Float64,
    'input' : ProjectInput,
    'asciiSingleLineDiagram' : IDL.Text,
    'globalWarnings' : IDL.Vec(IDL.Text),
    'groupingFactor' : IDL.Float64,
    'demandFormulaSteps' : IDL.Vec(FormulaStep),
    'lineCurrentA' : IDL.Float64,
    'powerFactorCompensation' : PowerFactorCompensation,
    'maxDemandVA' : IDL.Float64,
  });
  const Timestamp = IDL.Int;
  const Project = IDL.Record({
    'id' : ProjectId,
    'result' : IDL.Opt(CalculationResult),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'input' : ProjectInput,
  });
  
  return IDL.Service({
    'calculateProject' : IDL.Func([IDL.Text], [IDL.Opt(CalculationResult)], []),
    'createProject' : IDL.Func([ProjectInput], [IDL.Text], []),
    'deleteProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'updateProjectInput' : IDL.Func([IDL.Text, ProjectInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };