/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalculationResult {
  'circuits' : Array<CircuitDesign>,
  'shortCircuitFormulaSteps' : Array<FormulaStep>,
  'transformer' : [] | [TransformerResult],
  'asciiFloorPlan' : string,
  'energyEstimate' : EnergyEstimate,
  'totalInstalledPowerVA' : number,
  'projectId' : ProjectId,
  'materialsList' : Array<[string, bigint, string]>,
  'temperatureFactor' : number,
  'shortCircuitCurrentA' : number,
  'input' : ProjectInput,
  'asciiSingleLineDiagram' : string,
  'globalWarnings' : Array<string>,
  'groupingFactor' : number,
  'demandFormulaSteps' : Array<FormulaStep>,
  'lineCurrentA' : number,
  'powerFactorCompensation' : PowerFactorCompensation,
  'maxDemandVA' : number,
}
export interface CircuitDesign {
  'id' : string,
  'totalPowerVA' : number,
  'formulaSteps' : Array<FormulaStep>,
  'correctedCurrentA' : number,
  'voltageDropPct' : number,
  'cableSectionMm2' : number,
  'description' : string,
  'compliesNB777' : boolean,
  'warnings' : Array<string>,
  'itmAmperes' : bigint,
  'circuitType' : CircuitType,
  'nominalCurrentA' : number,
  'points' : bigint,
}
export type CircuitType = { 'lighting' : null } |
  { 'power' : null } |
  { 'common' : null };
export interface CommonOutletLoad { 'quantity' : bigint }
export type ConductorInsulation = { 'pvc' : null } |
  { 'xlpe' : null };
export type ConductorMaterial = { 'aluminum' : null } |
  { 'copper' : null };
export interface ConductorType {
  'insulation' : ConductorInsulation,
  'material' : ConductorMaterial,
}
export interface EnergyEstimate {
  'dailyUsageHours' : number,
  'dailyKWh' : number,
  'estimatedMonthlyCostBs' : number,
  'monthlyKWh' : number,
}
export interface FormulaStep {
  'result' : number,
  'expression' : string,
  'name' : string,
  'nb777Ref' : string,
  'unit' : string,
  'substitution' : string,
}
export type InstallationType = { 'residential' : null } |
  { 'industrial' : null };
export interface LuminaireLoad {
  'typ' : string,
  'unitPowerW' : number,
  'quantity' : bigint,
}
export interface PowerFactorCompensation {
  'reactiveKVAR' : number,
  'formulaSteps' : Array<FormulaStep>,
  'suggestedBankKVAR' : number,
  'needed' : boolean,
  'capacitorMicroFarads' : number,
}
export interface PowerOutletLoad {
  'voltage' : number,
  'efficiency' : number,
  'name' : string,
  'powerKW' : number,
  'isWetArea' : boolean,
  'cosPhi' : number,
}
export interface Project {
  'id' : ProjectId,
  'result' : [] | [CalculationResult],
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'input' : ProjectInput,
}
export type ProjectId = string;
export interface ProjectInput {
  'installationType' : InstallationType,
  'luminaires' : Array<LuminaireLoad>,
  'existingTransformerKVA' : [] | [number],
  'transformerMode' : TransformerMode,
  'floors' : bigint,
  'name' : string,
  'ambientTempC' : number,
  'powerOutlets' : Array<PowerOutletLoad>,
  'totalAreaM2' : number,
  'distanceToTransformerM' : number,
  'conductorType' : ConductorType,
  'voltageSystem' : VoltageSystem,
  'initialPowerFactor' : number,
  'commonOutlets' : Array<CommonOutletLoad>,
}
export type Timestamp = bigint;
export type TransformerMode = { 'own' : null } |
  { 'existing' : null };
export interface TransformerResult {
  'formulaSteps' : Array<FormulaStep>,
  'primaryCurrentA' : number,
  'selectedKVA' : number,
  'requiredKVA' : number,
  'secondaryCurrentA' : number,
  'isExistingAdequate' : [] | [boolean],
}
export type VoltageSystem = { 'tri220' : null } |
  { 'tri380' : null } |
  { 'mono220' : null };
export interface _SERVICE {
  'calculateProject' : ActorMethod<[string], [] | [CalculationResult]>,
  'createProject' : ActorMethod<[ProjectInput], string>,
  'deleteProject' : ActorMethod<[string], boolean>,
  'getProject' : ActorMethod<[string], [] | [Project]>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'updateProjectInput' : ActorMethod<[string, ProjectInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];