/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LuminaireLoad {
    typ: string;
    unitPowerW: number;
    quantity: bigint;
}
export type Timestamp = bigint;
export interface PowerOutletLoad {
    voltage: number;
    efficiency: number;
    name: string;
    powerKW: number;
    isWetArea: boolean;
    cosPhi: number;
}
export interface EnergyEstimate {
    dailyUsageHours: number;
    dailyKWh: number;
    estimatedMonthlyCostBs: number;
    monthlyKWh: number;
}
export interface CalculationResult {
    circuits: Array<CircuitDesign>;
    shortCircuitFormulaSteps: Array<FormulaStep>;
    transformer?: TransformerResult;
    asciiFloorPlan: string;
    energyEstimate: EnergyEstimate;
    totalInstalledPowerVA: number;
    projectId: ProjectId;
    materialsList: Array<[string, bigint, string]>;
    temperatureFactor: number;
    shortCircuitCurrentA: number;
    input: ProjectInput;
    asciiSingleLineDiagram: string;
    globalWarnings: Array<string>;
    groupingFactor: number;
    demandFormulaSteps: Array<FormulaStep>;
    lineCurrentA: number;
    powerFactorCompensation: PowerFactorCompensation;
    maxDemandVA: number;
}
export interface TransformerResult {
    formulaSteps: Array<FormulaStep>;
    primaryCurrentA: number;
    selectedKVA: number;
    requiredKVA: number;
    secondaryCurrentA: number;
    isExistingAdequate?: boolean;
}
export interface CircuitDesign {
    id: string;
    totalPowerVA: number;
    formulaSteps: Array<FormulaStep>;
    correctedCurrentA: number;
    voltageDropPct: number;
    cableSectionMm2: number;
    description: string;
    compliesNB777: boolean;
    warnings: Array<string>;
    itmAmperes: bigint;
    circuitType: CircuitType;
    nominalCurrentA: number;
    points: bigint;
}
export interface ProjectInput {
    installationType: InstallationType;
    luminaires: Array<LuminaireLoad>;
    existingTransformerKVA?: number;
    transformerMode: TransformerMode;
    floors: bigint;
    name: string;
    ambientTempC: number;
    powerOutlets: Array<PowerOutletLoad>;
    totalAreaM2: number;
    distanceToTransformerM: number;
    conductorType: ConductorType;
    voltageSystem: VoltageSystem;
    initialPowerFactor: number;
    commonOutlets: Array<CommonOutletLoad>;
}
export interface CommonOutletLoad {
    quantity: bigint;
}
export type ProjectId = string;
export interface ConductorType {
    insulation: ConductorInsulation;
    material: ConductorMaterial;
}
export interface Project {
    id: ProjectId;
    result?: CalculationResult;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    input: ProjectInput;
}
export interface PowerFactorCompensation {
    reactiveKVAR: number;
    formulaSteps: Array<FormulaStep>;
    suggestedBankKVAR: number;
    needed: boolean;
    capacitorMicroFarads: number;
}
export interface FormulaStep {
    result: number;
    expression: string;
    name: string;
    nb777Ref: string;
    unit: string;
    substitution: string;
}
export enum CircuitType {
    lighting = "lighting",
    power = "power",
    common = "common"
}
export enum ConductorInsulation {
    pvc = "pvc",
    xlpe = "xlpe"
}
export enum ConductorMaterial {
    aluminum = "aluminum",
    copper = "copper"
}
export enum InstallationType {
    residential = "residential",
    industrial = "industrial"
}
export enum TransformerMode {
    own = "own",
    existing = "existing"
}
export enum VoltageSystem {
    tri220 = "tri220",
    tri380 = "tri380",
    mono220 = "mono220"
}
export interface backendInterface {
    calculateProject(projectId: string): Promise<CalculationResult | null>;
    createProject(input: ProjectInput): Promise<string>;
    deleteProject(id: string): Promise<boolean>;
    getProject(id: string): Promise<Project | null>;
    listProjects(): Promise<Array<Project>>;
    updateProjectInput(id: string, input: ProjectInput): Promise<boolean>;
}
import type { CalculationResult as _CalculationResult, CircuitDesign as _CircuitDesign, CircuitType as _CircuitType, CommonOutletLoad as _CommonOutletLoad, ConductorInsulation as _ConductorInsulation, ConductorMaterial as _ConductorMaterial, ConductorType as _ConductorType, EnergyEstimate as _EnergyEstimate, FormulaStep as _FormulaStep, InstallationType as _InstallationType, LuminaireLoad as _LuminaireLoad, PowerFactorCompensation as _PowerFactorCompensation, PowerOutletLoad as _PowerOutletLoad, Project as _Project, ProjectId as _ProjectId, ProjectInput as _ProjectInput, Timestamp as _Timestamp, TransformerMode as _TransformerMode, TransformerResult as _TransformerResult, VoltageSystem as _VoltageSystem } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateProject(arg0: string): Promise<CalculationResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateProject(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateProject(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProject(arg0: ProjectInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_ProjectInput_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_ProjectInput_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getProject(arg0: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProjectInput(arg0: string, arg1: ProjectInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectInput(arg0, to_candid_ProjectInput_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectInput(arg0, to_candid_ProjectInput_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CalculationResult_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalculationResult): CalculationResult {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_CircuitDesign_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CircuitDesign): CircuitDesign {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CircuitType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CircuitType): CircuitType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ConductorInsulation_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConductorInsulation): ConductorInsulation {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ConductorMaterial_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConductorMaterial): ConductorMaterial {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ConductorType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConductorType): ConductorType {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_InstallationType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InstallationType): InstallationType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectInput): ProjectInput {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_TransformerMode_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransformerMode): TransformerMode {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TransformerResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransformerResult): TransformerResult {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_VoltageSystem_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoltageSystem): VoltageSystem {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CalculationResult]): CalculationResult | null {
    return value.length === 0 ? null : from_candid_CalculationResult_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransformerResult]): TransformerResult | null {
    return value.length === 0 ? null : from_candid_TransformerResult_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    formulaSteps: Array<_FormulaStep>;
    primaryCurrentA: number;
    selectedKVA: number;
    requiredKVA: number;
    secondaryCurrentA: number;
    isExistingAdequate: [] | [boolean];
}): {
    formulaSteps: Array<FormulaStep>;
    primaryCurrentA: number;
    selectedKVA: number;
    requiredKVA: number;
    secondaryCurrentA: number;
    isExistingAdequate?: boolean;
} {
    return {
        formulaSteps: value.formulaSteps,
        primaryCurrentA: value.primaryCurrentA,
        selectedKVA: value.selectedKVA,
        requiredKVA: value.requiredKVA,
        secondaryCurrentA: value.secondaryCurrentA,
        isExistingAdequate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.isExistingAdequate))
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    installationType: _InstallationType;
    luminaires: Array<_LuminaireLoad>;
    existingTransformerKVA: [] | [number];
    transformerMode: _TransformerMode;
    floors: bigint;
    name: string;
    ambientTempC: number;
    powerOutlets: Array<_PowerOutletLoad>;
    totalAreaM2: number;
    distanceToTransformerM: number;
    conductorType: _ConductorType;
    voltageSystem: _VoltageSystem;
    initialPowerFactor: number;
    commonOutlets: Array<_CommonOutletLoad>;
}): {
    installationType: InstallationType;
    luminaires: Array<LuminaireLoad>;
    existingTransformerKVA?: number;
    transformerMode: TransformerMode;
    floors: bigint;
    name: string;
    ambientTempC: number;
    powerOutlets: Array<PowerOutletLoad>;
    totalAreaM2: number;
    distanceToTransformerM: number;
    conductorType: ConductorType;
    voltageSystem: VoltageSystem;
    initialPowerFactor: number;
    commonOutlets: Array<CommonOutletLoad>;
} {
    return {
        installationType: from_candid_InstallationType_n15(_uploadFile, _downloadFile, value.installationType),
        luminaires: value.luminaires,
        existingTransformerKVA: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.existingTransformerKVA)),
        transformerMode: from_candid_TransformerMode_n18(_uploadFile, _downloadFile, value.transformerMode),
        floors: value.floors,
        name: value.name,
        ambientTempC: value.ambientTempC,
        powerOutlets: value.powerOutlets,
        totalAreaM2: value.totalAreaM2,
        distanceToTransformerM: value.distanceToTransformerM,
        conductorType: from_candid_ConductorType_n20(_uploadFile, _downloadFile, value.conductorType),
        voltageSystem: from_candid_VoltageSystem_n26(_uploadFile, _downloadFile, value.voltageSystem),
        initialPowerFactor: value.initialPowerFactor,
        commonOutlets: value.commonOutlets
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insulation: _ConductorInsulation;
    material: _ConductorMaterial;
}): {
    insulation: ConductorInsulation;
    material: ConductorMaterial;
} {
    return {
        insulation: from_candid_ConductorInsulation_n22(_uploadFile, _downloadFile, value.insulation),
        material: from_candid_ConductorMaterial_n24(_uploadFile, _downloadFile, value.material)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    circuits: Array<_CircuitDesign>;
    shortCircuitFormulaSteps: Array<_FormulaStep>;
    transformer: [] | [_TransformerResult];
    asciiFloorPlan: string;
    energyEstimate: _EnergyEstimate;
    totalInstalledPowerVA: number;
    projectId: _ProjectId;
    materialsList: Array<[string, bigint, string]>;
    temperatureFactor: number;
    shortCircuitCurrentA: number;
    input: _ProjectInput;
    asciiSingleLineDiagram: string;
    globalWarnings: Array<string>;
    groupingFactor: number;
    demandFormulaSteps: Array<_FormulaStep>;
    lineCurrentA: number;
    powerFactorCompensation: _PowerFactorCompensation;
    maxDemandVA: number;
}): {
    circuits: Array<CircuitDesign>;
    shortCircuitFormulaSteps: Array<FormulaStep>;
    transformer?: TransformerResult;
    asciiFloorPlan: string;
    energyEstimate: EnergyEstimate;
    totalInstalledPowerVA: number;
    projectId: ProjectId;
    materialsList: Array<[string, bigint, string]>;
    temperatureFactor: number;
    shortCircuitCurrentA: number;
    input: ProjectInput;
    asciiSingleLineDiagram: string;
    globalWarnings: Array<string>;
    groupingFactor: number;
    demandFormulaSteps: Array<FormulaStep>;
    lineCurrentA: number;
    powerFactorCompensation: PowerFactorCompensation;
    maxDemandVA: number;
} {
    return {
        circuits: from_candid_vec_n4(_uploadFile, _downloadFile, value.circuits),
        shortCircuitFormulaSteps: value.shortCircuitFormulaSteps,
        transformer: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.transformer)),
        asciiFloorPlan: value.asciiFloorPlan,
        energyEstimate: value.energyEstimate,
        totalInstalledPowerVA: value.totalInstalledPowerVA,
        projectId: value.projectId,
        materialsList: value.materialsList,
        temperatureFactor: value.temperatureFactor,
        shortCircuitCurrentA: value.shortCircuitCurrentA,
        input: from_candid_ProjectInput_n13(_uploadFile, _downloadFile, value.input),
        asciiSingleLineDiagram: value.asciiSingleLineDiagram,
        globalWarnings: value.globalWarnings,
        groupingFactor: value.groupingFactor,
        demandFormulaSteps: value.demandFormulaSteps,
        lineCurrentA: value.lineCurrentA,
        powerFactorCompensation: value.powerFactorCompensation,
        maxDemandVA: value.maxDemandVA
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    result: [] | [_CalculationResult];
    name: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    input: _ProjectInput;
}): {
    id: ProjectId;
    result?: CalculationResult;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    input: ProjectInput;
} {
    return {
        id: value.id,
        result: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.result)),
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        input: from_candid_ProjectInput_n13(_uploadFile, _downloadFile, value.input)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    totalPowerVA: number;
    formulaSteps: Array<_FormulaStep>;
    correctedCurrentA: number;
    voltageDropPct: number;
    cableSectionMm2: number;
    description: string;
    compliesNB777: boolean;
    warnings: Array<string>;
    itmAmperes: bigint;
    circuitType: _CircuitType;
    nominalCurrentA: number;
    points: bigint;
}): {
    id: string;
    totalPowerVA: number;
    formulaSteps: Array<FormulaStep>;
    correctedCurrentA: number;
    voltageDropPct: number;
    cableSectionMm2: number;
    description: string;
    compliesNB777: boolean;
    warnings: Array<string>;
    itmAmperes: bigint;
    circuitType: CircuitType;
    nominalCurrentA: number;
    points: bigint;
} {
    return {
        id: value.id,
        totalPowerVA: value.totalPowerVA,
        formulaSteps: value.formulaSteps,
        correctedCurrentA: value.correctedCurrentA,
        voltageDropPct: value.voltageDropPct,
        cableSectionMm2: value.cableSectionMm2,
        description: value.description,
        compliesNB777: value.compliesNB777,
        warnings: value.warnings,
        itmAmperes: value.itmAmperes,
        circuitType: from_candid_CircuitType_n7(_uploadFile, _downloadFile, value.circuitType),
        nominalCurrentA: value.nominalCurrentA,
        points: value.points
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    residential: null;
} | {
    industrial: null;
}): InstallationType {
    return "residential" in value ? InstallationType.residential : "industrial" in value ? InstallationType.industrial : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    own: null;
} | {
    existing: null;
}): TransformerMode {
    return "own" in value ? TransformerMode.own : "existing" in value ? TransformerMode.existing : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pvc: null;
} | {
    xlpe: null;
}): ConductorInsulation {
    return "pvc" in value ? ConductorInsulation.pvc : "xlpe" in value ? ConductorInsulation.xlpe : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aluminum: null;
} | {
    copper: null;
}): ConductorMaterial {
    return "aluminum" in value ? ConductorMaterial.aluminum : "copper" in value ? ConductorMaterial.copper : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tri220: null;
} | {
    tri380: null;
} | {
    mono220: null;
}): VoltageSystem {
    return "tri220" in value ? VoltageSystem.tri220 : "tri380" in value ? VoltageSystem.tri380 : "mono220" in value ? VoltageSystem.mono220 : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lighting: null;
} | {
    power: null;
} | {
    common: null;
}): CircuitType {
    return "lighting" in value ? CircuitType.lighting : "power" in value ? CircuitType.power : "common" in value ? CircuitType.common : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CircuitDesign>): Array<CircuitDesign> {
    return value.map((x)=>from_candid_CircuitDesign_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n43(_uploadFile, _downloadFile, x));
}
function to_candid_ConductorInsulation_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConductorInsulation): _ConductorInsulation {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_ConductorMaterial_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConductorMaterial): _ConductorMaterial {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_ConductorType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConductorType): _ConductorType {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_InstallationType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InstallationType): _InstallationType {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectInput_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectInput): _ProjectInput {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_TransformerMode_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransformerMode): _TransformerMode {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_VoltageSystem_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoltageSystem): _VoltageSystem {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    installationType: InstallationType;
    luminaires: Array<LuminaireLoad>;
    existingTransformerKVA?: number;
    transformerMode: TransformerMode;
    floors: bigint;
    name: string;
    ambientTempC: number;
    powerOutlets: Array<PowerOutletLoad>;
    totalAreaM2: number;
    distanceToTransformerM: number;
    conductorType: ConductorType;
    voltageSystem: VoltageSystem;
    initialPowerFactor: number;
    commonOutlets: Array<CommonOutletLoad>;
}): {
    installationType: _InstallationType;
    luminaires: Array<_LuminaireLoad>;
    existingTransformerKVA: [] | [number];
    transformerMode: _TransformerMode;
    floors: bigint;
    name: string;
    ambientTempC: number;
    powerOutlets: Array<_PowerOutletLoad>;
    totalAreaM2: number;
    distanceToTransformerM: number;
    conductorType: _ConductorType;
    voltageSystem: _VoltageSystem;
    initialPowerFactor: number;
    commonOutlets: Array<_CommonOutletLoad>;
} {
    return {
        installationType: to_candid_InstallationType_n30(_uploadFile, _downloadFile, value.installationType),
        luminaires: value.luminaires,
        existingTransformerKVA: value.existingTransformerKVA ? candid_some(value.existingTransformerKVA) : candid_none(),
        transformerMode: to_candid_TransformerMode_n32(_uploadFile, _downloadFile, value.transformerMode),
        floors: value.floors,
        name: value.name,
        ambientTempC: value.ambientTempC,
        powerOutlets: value.powerOutlets,
        totalAreaM2: value.totalAreaM2,
        distanceToTransformerM: value.distanceToTransformerM,
        conductorType: to_candid_ConductorType_n34(_uploadFile, _downloadFile, value.conductorType),
        voltageSystem: to_candid_VoltageSystem_n40(_uploadFile, _downloadFile, value.voltageSystem),
        initialPowerFactor: value.initialPowerFactor,
        commonOutlets: value.commonOutlets
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insulation: ConductorInsulation;
    material: ConductorMaterial;
}): {
    insulation: _ConductorInsulation;
    material: _ConductorMaterial;
} {
    return {
        insulation: to_candid_ConductorInsulation_n36(_uploadFile, _downloadFile, value.insulation),
        material: to_candid_ConductorMaterial_n38(_uploadFile, _downloadFile, value.material)
    };
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InstallationType): {
    residential: null;
} | {
    industrial: null;
} {
    return value == InstallationType.residential ? {
        residential: null
    } : value == InstallationType.industrial ? {
        industrial: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransformerMode): {
    own: null;
} | {
    existing: null;
} {
    return value == TransformerMode.own ? {
        own: null
    } : value == TransformerMode.existing ? {
        existing: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConductorInsulation): {
    pvc: null;
} | {
    xlpe: null;
} {
    return value == ConductorInsulation.pvc ? {
        pvc: null
    } : value == ConductorInsulation.xlpe ? {
        xlpe: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConductorMaterial): {
    aluminum: null;
} | {
    copper: null;
} {
    return value == ConductorMaterial.aluminum ? {
        aluminum: null
    } : value == ConductorMaterial.copper ? {
        copper: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoltageSystem): {
    tri220: null;
} | {
    tri380: null;
} | {
    mono220: null;
} {
    return value == VoltageSystem.tri220 ? {
        tri220: null
    } : value == VoltageSystem.tri380 ? {
        tri380: null
    } : value == VoltageSystem.mono220 ? {
        mono220: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
